@startuml

enum AbioticFactor {
  AIR
  SOIL
  WATER
}

enum MeasurementType {
  CO2_GAS (parts per million 0 to 100,000)
  TEMPERATURE (degrees Celcius –40 to 135°C)
  PH (values 0 to 14)
  LUX (values 0 to 150,000)
}

class Measurement {
  abioticFactor: AbioticFactor
  value: Double
  type: MeasurementType
}

class Note {
  note: String
}

class Organization {
  name: String
  description: String
  code: String
}

class Photo {
  base64: String
}

enum Role {
  OWNER
  MEMBER
}

class Survey {
  date: Date 
}

class Site {
  name: String
  description: String
  latitude: Double
  longitude: Double
  altitude: Double
}

class User {
  name: String
  email: String
  password: String
}

User ..> Organization: creates
User ..> Site: defines
User ..> Survey: takes

Measurement -- AbioticFactor
Measurement -- MeasurementType

User "0" o-- "*" Organization: belongs
(User, Organization) .. Role
Organization "0" *-- "*" Site

Site "0" *-- "*" Survey

Survey "0" *-- "*" Note
Survey "0" *-- "*" Photo
Survey "0" *-- "*" Measurement

@enduml