@startuml

enum AbioticFactor {
  AIR
  SOIL
  WATER
}

enum MeasurementUnit {
  ACIDITY_PH (0..14)
  CARBON_DIOXIDE_PPM (0..100,000)
  LIGHT_INTENSITY_LUX (0..150,000)
  TEMPERATURE_CELCIUS (-270..1000)
}

class Measurement {
  abioticFactor: AbioticFactor
  value: Double
  type: MeasurementUnit
}

class Note {
  note: String
}

class Organization {
  name: String
  description: String
  code: String
}

class Photo {
  base64: String
}

enum Role {
  OWNER
  MEMBER
}

class Survey {
  date: Date 
}

class Site {
  name: String
  description: String
  latitude: Double
  longitude: Double
  altitude: Double
  horizontalAccuracy: Double
  verticalAccuracy: Double
}

class User {
  name: String
  email: String
  password: String
}

User ..> Organization: creates
User ..> Site: defines
User ..> Survey: takes

Measurement -- AbioticFactor
Measurement -- MeasurementUnit

User "0" o-- "*" Organization: belongs
(User, Organization) .. Role
Organization "0" *-- "*" Site

Site "0" *-- "*" Survey

Survey "0" *-- "*" Note
Survey "0" *-- "*" Photo
Survey "0" *-- "*" Measurement

@enduml